### ISSUE TITLE
Can you explain what you meant by this? It's not clear to me, so I can't suggest how to make it clearer.

### ISSUE THREAD

**Issue by JayLoomis** [astralfrontier/flip-a-card#57]
https://github.com/astralfrontier/flip-a-card/blob/cf0f56592c44d099c60c376ed26396dbce5184bc/card-data/01-character-role.yaml#L49

**Comment by astralfrontier** [comment]
Ahahah, that's a tough one, sorry to do that to you.

It should be something more like "make use of your monstrous qualities". There's some overlap with the previous prompt, "Use others' fears to your advantage", as well.

Scenarios for the card:

- a minotaur gores someone with their horns
- an untouchable caste member spies on a scene because nobody wants to acknowledge them
- a half-orc uses their primal rage to gain advantage in combat
- a feared pirate causes enemies to throw down their weapons rather than fight
- a tiefling leverages their infernal reputation to get access to a warlock's sanctum
